---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaS3BucketPrefix:
    Description: 'the bucket prefix of the lambda distribution bucket'
    Type: String
    Default: binxio-public

Resources:
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Resource: "*"
          Action:
          - ec2:DescribeAddresses
          - ec2:AssociateAddress
          - ec2:DisassociateAddress

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - !Ref Policy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Description: Elastic IP manager for Autoscaling Group instances
      Code:
        S3Key: lambdas/asg-elastic-ip-manager-latest.zip
        S3Bucket: !Sub '${LambdaS3BucketPrefix}-${AWS::Region}'
      Handler: asg_elastic_ip_manager.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python2.7
      Environment:
        Variables:
          AUTO_SCALING_GROUP_NAMES: 'bastion'

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt Function.Arn
      Principal: events.amazonaws.com

  Rule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern: !Sub |
        {
          "source": [ "aws.autoscaling" ],
          "detail": {
            "LifecycleTransition": ["autoscaling:EC2_INSTANCE_TERMINATING", "autoscaling:EC2_INSTANCE_LAUNCHING"]
          }
        }
      Targets:
      - Arn: !GetAtt Function.Arn
        Id: asg-elastic-ip-manager
