---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaS3Bucket:
    Type: String
    Default: ''
  CFNCustomProviderZipFileName:
    Type: String
    Default: lambdas/asg-elastic-ip-manager-latest.zip

Resources:
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Resource: "*"
          Action:
          - ec2:DescribeAddresses
          - ec2:AssociateAddress
          - ec2:DisassociateAddress
          - autoscaling:DescribeAutoScalingGroups

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - !Ref Policy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Description: Elastic IP manager for Autoscaling Group instances
      Code:
        S3Bucket: !If
          - UsePublicBucket
          - !Sub 'binxio-public-${AWS::Region}'
          - !Ref 'LambdaS3Bucket'
        S3Key: !Ref 'CFNCustomProviderZipFileName'
      Handler: asg_elastic_ip_manager.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
      Environment:
        Variables:
          AUTO_SCALING_GROUP_NAMES: 'bastion'

  AsgElasticIPManager:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: AsgElasticIPManager
      DisplayName: Autoscaling elastic IP manager
      Subscription:
        - Endpoint: !GetAtt 'Function.Arn'
          Protocol: lambda

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt Function.Arn
      Principal: sns.amazonaws.com
